# Generated by Django 4.1.5 on 2023-03-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rango", "0005_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
